language: java
jdk:
- oraclejdk7
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- bash ./deploy-test.sh
before_script:
- 
script:
- mvn package -Pbuild-distr -Pspark-1.5 -Phadoop-2.6 -Ppyspark -B -Dmaven.test.skip=true
  -DskipTests
after_failure:
- cat target/rat.txt
- cat zeppelin-server/target/rat.txt
- cat zeppelin-distribution/target/zeppelin-*-SNAPSHOT/zeppelin-*-SNAPSHOT/logs/zeppelin*.log
- cat zeppelin-distribution/target/zeppelin-*-SNAPSHOT/zeppelin-*-SNAPSHOT/logs/zeppelin*.out
after_script:
- 
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
env:
  global:
  - GH_REF: github.com/kabong009/incubator-zeppelin.git
  - secure: qq/pMTi19kwBPmffQbCPgeq8HIZqAS08HFv0lMJevhGyG7VPbTOAT+Lao+riOiUuSXeUx+s6Q8JpYf72Nr3AHUNlNIeqMNEcP2vpBCYJLx4rkJ6MCk9S94kNVRnOMoOfazvVpimq7NeIijEvDndxBzE2dRYsz2k2pKwzUCYkUE5oiFhYFbzoihx0qPxZfw+gY0Q5UvF33OvZc9ung20Ra29TjmKoBeGFl7sDU/H0SCCjmQLaAtWwonFBJMyVVQ8qrwP+Ydr8yKjAo+/+WciRI1CAjonxuVArfRVg5gbWwPiD3gJSjAiGbcahirjR1tH6WqObxf4JZA4H11uAbVCk0pieLYTcGn1kn61N5l9O+XByZhZR5tQ279/QZMij8fBsDXsUBz7V380sgHfiu6t3QxChy4YNdIidIYnF5+n3h+l+PDEopdm2WC/YZtlkjDO49WSnLkSJDEvFxY2pKfx9WcTjExfDZALdacQeO/O8byGGgRCnmeLzyxhieTipYt2NQRxx0wAkiyf7l/DdcZZzYCpVEQ//85q9ygemeKr642n/z+Bh15E6j4mT0OeoJbAyAzHG54LbwIDdzjShVNLZvn20f7U+qzNenmWu6lNxCsdOF3zPWbw2U0hDdbR7aeHktcVUdtJ+M/C6rqGIogWtD+dtxBFjtpWzJV5GypwVgk8=
