language: java
jdk:
- oraclejdk7
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- mvn package -Pbuild-distr -Pspark-1.5 -Phadoop-2.6 -Ppyspark -B -DskipTests
before_deploy:
- bash ./prepare-s3.sh
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIOTL54CLBJF7LWPQ
  secret_access_key:
    secure: NfSwAQ9Ic+7mtG9Pod1DW+/Ztv/guBkbPwWRPQxEPIcAsY6gNfNV4Uw1yh1qGiE0rj8RKMBEa6TiH3saRPpFY/lvwv/EAHmoPYLgTbKLBM1lLnw8xEtLQufuU2fCrpSQPCFiatu92/wElXJY1HTIamZ/IEyhNUgIo2oi8UccxE4F09bNN2W96mCZihaUhVg+ug7XzJHSVxQEV8D+626dIUnoFJafnyjKcAMuEM367W5iVExukYCniLlhnxwIIGkQTxFpWOfdHgr3vh658lcG4Bbr0J5tswFwsqn1fRsEgpdZEzznLFgFhxMLvfa/ANd2q2byuu63FS14DC4brt2O5wIsvTMHfnAayOOEDf4m1FtJLic7upC1BsKxYAcOIFaP5VXMZs/T/m5A3l3gDbS+vtZS4sR2sSxRJXCKoNA2uUKxCgSRQNIBsI/Z198Pye5lHoZd3/7bUTNmvNhO7jg0wLSpjGEguJYQoBpkktEe4KOlmK+xlu2mNqLA03mT351FF9a4zy9kWAxSKA/8a2Ssas8yUvoxDL4RxUlBT/ZP+b9QbLAYed+04BEnpQ/XbhBmFc4LSnVFz0WuRTFNJBYMpEJL6VRwZ7+EfvnZPgrdFdSWdAe3jqnF97DMHXvyMxkzF0dWeGIZxNKuLDcBr8eFSb9jrsywnjm+b7ayHL6gobI=
  bucket: kbng-zeppelin
  region: us-east-1
  local_dir: s3-source
  detect_encoding: true
after_failure:
- cat target/rat.txt
- cat zeppelin-server/target/rat.txt
- cat zeppelin-distribution/target/zeppelin-*-SNAPSHOT/zeppelin-*-SNAPSHOT/logs/zeppelin*.log
- cat zeppelin-distribution/target/zeppelin-*-SNAPSHOT/zeppelin-*-SNAPSHOT/logs/zeppelin*.out
