language: java
jdk:
- oraclejdk7
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- 
script:
- mvn package -Pbuild-distr -Pspark-1.5 -Phadoop-2.6 -Ppyspark -B -Dmaven.test.skip=true
  -DskipTests
after_failure:
- cat target/rat.txt
- cat zeppelin-server/target/rat.txt
- cat zeppelin-distribution/target/zeppelin-*-SNAPSHOT/zeppelin-*-SNAPSHOT/logs/zeppelin*.log
- cat zeppelin-distribution/target/zeppelin-*-SNAPSHOT/zeppelin-*-SNAPSHOT/logs/zeppelin*.out
after_script:
- 
#notifications:
#  slack:
#    secure: dtIkPwlf5uTun19p9TtPEAFmrLOMK2COE8TL9m8LXX/N2WzJaKYvAnovMObEV6KEgK2oZ+72Cke7eBI+Hp4FmHZ2B7mQI/PNCfRZthI3cc3zVmMd25yvLH9AlCRa2bC6R885z2copvzaoZtLBkHnPa8bUrUkbmRp40qkDPQpgO4=
#deploy:
#  provider: bintray
#  file: bintray-deploy.json
#  user: kabong009
#  key:
#    secure: RC8/4aX3oPDBcZ/QQAUdtpEZQA9jZoGTjhqF/+2tOD0MyNJvAtajXeefG+UZI3FYrRzCMu/8/lGTt+ohFNzdeuPyxA/8Jh5bH86OBHerj1bJ3t/kX5orhkkpmYZI7TgaEM5KWuPQmd4R2BAWALVLH9qQucAhcbfwWsSmgHxogaQwxEWp7wLRA+Flpl4AzYAI21amEew0V0oscKx0jY7yxOOuqsw2p1M/EzF/T6HPdb6KmKBnyjaiAu0lNOPQoulLrmh9TkRs19nMlJE6p/Ky0Thv/j5DtaJP1XJlCHgFcZzfa/FtzXYHloebsr2L0HU1aquoU/zHKRFobQH2/4fydC1wL3yMZ4eSFZ8j/Q+DfYOOvgflu0oeODU+rTaztQ0WA3DdJMU2DvYX+619WKQ4udLlYsTeo0bMEbtabZ/Gy/OFztIw6tTRkwRd6tUQ5WBvro6qxU1FuHcakUbKw64XpIbryB6v8dcMacPB5jBZZEENF3JQdxGMUVOsQt+NOZ3aPvUml5iTMqAxCQpR21GGm+BKHHKDJMklTW62Y1RtSUTTS9pXB8O+3d0wTD0zcAPtYYTSmbl7lrS33bp7MSNSTP0cMARYkFlhZyj2+sOgNhfayN1nxOKbrrj1B/HhnnKg5R4Enam1wCTdiz4lCpeWuhv8E+XB1HQ67khYC0PeWqk=

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
	
env:
  global:
    GH_REF: github.com/kabong009/incubator-zeppelin.git
    secure: BqZwb1+3xzfC/4/ZPm4K2Z5Q3BU1AjCVXR2NKVHKAj0oKiGkVYYA0ofxQAKQ8oHSSey2phqOm3zIMF5+YaPu8U+xSaAupiO1asrZ5ON/LnG6FdN3Vn9gz0K/huN29DQveOu/3S7rxMtZA6We7heIdkFdEjnjB/2XIPamRSovr9mcNV3UFFDkxC0bHRdceaxtoTYqasyXMP7mMvRlt5nzstkNfONZiE7x+aAgjtVsr8FXUEjJ21d35mub1hMR9cjekRiBhu1AGk5x7mBC0PyUVDJjMypXKhdCb8aGmM7OL0gOZbJVeineNA1snbFkXv0N8pyxxjAErLYqfk1C4M4qP1kQviGCUYRy75NL3DNzCsgkcd7fzCORrDBmCKzsy/YPGjclTezC60xVuNOM8twJ7u2G6g+MWIDPTqjoW8aqJwaY2PpPTR9smSPV16BdKI/4u5EriHxq+OnbKTnoa/zSANitMWWHYqNUC/xMuEH2YsG7ppLUQcUR7L4rvMJubgtiQ/IE4ZjfZxZPWKkjhHZDl7HAEBjqTeLgrELPdxdi8GraL3h3ltSV9LmpqvRln+7dGEYHyZI/qdEfweY1B36h034P2LXCexn/SPh4zJCSPFaLPuGosrrDrQu5Drs39wzKxPzE3/dWoKzAE1EsPQSQanElt+1TZh426ac1FsoF/Jc=
