language: java
jdk:
- oraclejdk7
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
# - bash ./deploy-test.sh
before_script:
- 
script:
- mvn package -Pbuild-distr -Pspark-1.5 -Phadoop-2.6 -Ppyspark -B -Dmaven.test.skip=true
  -DskipTests
after_failure:
- cat target/rat.txt
- cat zeppelin-server/target/rat.txt
- cat zeppelin-distribution/target/zeppelin-*-SNAPSHOT/zeppelin-*-SNAPSHOT/logs/zeppelin*.log
- cat zeppelin-distribution/target/zeppelin-*-SNAPSHOT/zeppelin-*-SNAPSHOT/logs/zeppelin*.out
after_script:
- 
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
env:
  global:
  - GH_REF: github.com/kabong009/incubator-zeppelin.git
  - secure: DgCXGwBfWJ9o5C96T89BZxVn/Ib79G1t4bwAg8Hv99d96sWbCQMUVJg0bp5TE18Bcmx61FVfzH6gX5UCJ/pqTVobiE1fbW0EEpwWi0Fi+4NBizswXwuxtc8j/LGIuNcql8jY1tQ5+uCzo3+9lLjYRGGv4/nODu2BEDgAzT4Ge3kcTIZnGT7pAlSRWtEyT3ZddUR7/0rbi9TUQfmbyHn4yTEuPEeyOGvCy3chD4pAHsC8OWjxAQnFM58/Z9XrBibktw2aIKhqYDL/yvETn2R7BrmyWeclHyLDUtddE/+7cY0WVb9EX1e7+G4tdLtTYmd8Y1E1h/md+qd85YzClSSCMmv3UkdZMzM44vw8sblYsuxVsP0ZWKjd/LESY1iQ3NIuvcVyY/x+hx2vn5UpgR3SvnwbJhvImEFjJcM1mmNu2JbyNoLYLNtfKhU8XCKK0LAiUr3U7sVSqyrlF3qPgz8pKy8A+nwYOLOaXlwtZ/6/1yxg0SDQoB1K2tdnFV41Ac2lyqBLkv7SdEQPFJHriSOHIsl74Pi6yDyl0B3q/vFURrvWvqT1U3N7RMbrTgxh9JKqXkROTX+b51iEugPSy6KHhvQrUWPGFVAcoPlMI6xyxVIrrL/FNlrVcMjUo3RZbaXmNPrn9z/x19CPMxg0mMM6YA4fisBJvPiF4QxPP2iI0LU=
